// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package leaderboarddb

import (
	"time"

	"github.com/google/uuid"
)

type LeaderboardOptin struct {
	UserID      uuid.UUID
	DisplayName string
	OptedInAt   time.Time
}
