// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package leaderboarddb

import (
	"context"

	"github.com/google/uuid"
)

const board = `-- name: Board :many
WITH first_pass AS (
    SELECT DISTINCT ON (user_id, lesson_slug)
        user_id, lesson_slug, provenance
    FROM exercise_attempt
    WHERE passed
    ORDER BY user_id, lesson_slug, created_at
)
SELECT
    o.display_name,
    count(*) FILTER (
        WHERE fp.provenance = 'typed' AND ul.solution_revealed_at IS NULL
    )::bigint AS solo,
    count(*) FILTER (
        WHERE NOT (fp.provenance = 'typed' AND ul.solution_revealed_at IS NULL)
    )::bigint AS assisted
FROM leaderboard_optin o
LEFT JOIN first_pass fp ON fp.user_id = o.user_id
LEFT JOIN user_lesson ul
       ON ul.user_id = fp.user_id AND ul.lesson_slug = fp.lesson_slug
GROUP BY o.user_id, o.display_name
ORDER BY solo DESC, assisted DESC, o.display_name
LIMIT $1
`

type BoardRow struct {
	DisplayName string
	Solo        int64
	Assisted    int64
}

// Both counts for every opted-in learner, in one pass.
//
// first_pass reduces each learner's attempts to the *first* one that passed per
// lesson, which is the only attempt whose provenance means anything: a learner
// who solves a lesson unaided and later pastes the same answer back in has not
// retroactively cheated, and one who pastes it first has not earned the solo
// count by retyping it afterwards.
//
// Solo requires two things and it is worth being explicit about both. The first
// passing attempt was typed, and the answer was never revealed — a lesson
// finished after reading the solution is still finished, but it is not solved
// unaided.
//
// Everything else that passed is assisted, which includes every submission that
// arrived over MCP.
func (q *Queries) Board(ctx context.Context, limit int32) ([]BoardRow, error) {
	rows, err := q.db.Query(ctx, board, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoardRow{}
	for rows.Next() {
		var i BoardRow
		if err := rows.Scan(&i.DisplayName, &i.Solo, &i.Assisted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOptIn = `-- name: GetOptIn :one
SELECT user_id, display_name, opted_in_at FROM leaderboard_optin
WHERE user_id = $1
`

func (q *Queries) GetOptIn(ctx context.Context, userID uuid.UUID) (LeaderboardOptin, error) {
	row := q.db.QueryRow(ctx, getOptIn, userID)
	var i LeaderboardOptin
	err := row.Scan(&i.UserID, &i.DisplayName, &i.OptedInAt)
	return i, err
}

const optIn = `-- name: OptIn :one

INSERT INTO leaderboard_optin (user_id, display_name)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE
SET display_name = excluded.display_name
RETURNING user_id, display_name, opted_in_at
`

type OptInParams struct {
	UserID      uuid.UUID
	DisplayName string
}

// Queries for the two boards.
//
// Only learners with a row in leaderboard_optin appear anywhere here. That is
// not a filter applied on top of the boards — it is the join they start from,
// so there is no ordering of this file in which a learner who never opted in
// can be listed.
// Upsert rather than insert, so changing a display name is the same action as
// choosing one and needs no separate route.
func (q *Queries) OptIn(ctx context.Context, arg OptInParams) (LeaderboardOptin, error) {
	row := q.db.QueryRow(ctx, optIn, arg.UserID, arg.DisplayName)
	var i LeaderboardOptin
	err := row.Scan(&i.UserID, &i.DisplayName, &i.OptedInAt)
	return i, err
}

const optOut = `-- name: OptOut :execrows
DELETE FROM leaderboard_optin
WHERE user_id = $1
`

func (q *Queries) OptOut(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, optOut, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
