package assets

import "embed"

// Assets carries everything the browser is served: the generated stylesheet,
// the fonts, and the JavaScript (vendored libraries plus our own).
//
// The directories are named rather than globbed on purpose. A pattern like
// `js/*` fails the build outright the moment a subdirectory under it is empty,
// which is a needless way to lose an afternoon; naming the directory embeds it
// whatever it happens to contain.
//
// css/output.css is generated by scripts/build-css.sh and is not committed, so
// a build with no stylesheet fails here at compile time instead of quietly
// serving an unstyled application.
//
//go:embed brand css fonts js
var Assets embed.FS
