// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package progressdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ExerciseAttempt struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	LessonSlug string
	Code       string
	Passed     bool
	CreatedAt  time.Time
}

type UserLesson struct {
	UserID             uuid.UUID
	LessonSlug         string
	Status             string
	StartedAt          time.Time
	CompletedAt        pgtype.Timestamptz
	SolutionRevealedAt pgtype.Timestamptz
}
