// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package progressdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countFailedAttempts = `-- name: CountFailedAttempts :one
SELECT count(*) FROM exercise_attempt
WHERE user_id = $1 AND lesson_slug = $2 AND passed = false
`

type CountFailedAttemptsParams struct {
	UserID     uuid.UUID
	LessonSlug string
}

// Drives when a hint and then the solution are offered. Counted rather than
// listed because the handler needs the number and nothing else, and the code
// column on these rows is the largest thing in the table.
func (q *Queries) CountFailedAttempts(ctx context.Context, arg CountFailedAttemptsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFailedAttempts, arg.UserID, arg.LessonSlug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLessonProgress = `-- name: GetLessonProgress :one
SELECT user_id, lesson_slug, status, started_at, completed_at, solution_revealed_at FROM user_lesson
WHERE user_id = $1 AND lesson_slug = $2
`

type GetLessonProgressParams struct {
	UserID     uuid.UUID
	LessonSlug string
}

func (q *Queries) GetLessonProgress(ctx context.Context, arg GetLessonProgressParams) (UserLesson, error) {
	row := q.db.QueryRow(ctx, getLessonProgress, arg.UserID, arg.LessonSlug)
	var i UserLesson
	err := row.Scan(
		&i.UserID,
		&i.LessonSlug,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.SolutionRevealedAt,
	)
	return i, err
}

const listAttempts = `-- name: ListAttempts :many
SELECT id, user_id, lesson_slug, code, passed, created_at FROM exercise_attempt
WHERE user_id = $1 AND lesson_slug = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListAttemptsParams struct {
	UserID     uuid.UUID
	LessonSlug string
	Limit      int32
}

func (q *Queries) ListAttempts(ctx context.Context, arg ListAttemptsParams) ([]ExerciseAttempt, error) {
	rows, err := q.db.Query(ctx, listAttempts, arg.UserID, arg.LessonSlug, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExerciseAttempt{}
	for rows.Next() {
		var i ExerciseAttempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LessonSlug,
			&i.Code,
			&i.Passed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgressForUser = `-- name: ListProgressForUser :many
SELECT user_id, lesson_slug, status, started_at, completed_at, solution_revealed_at FROM user_lesson
WHERE user_id = $1
ORDER BY lesson_slug
`

func (q *Queries) ListProgressForUser(ctx context.Context, userID uuid.UUID) ([]UserLesson, error) {
	rows, err := q.db.Query(ctx, listProgressForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserLesson{}
	for rows.Next() {
		var i UserLesson
		if err := rows.Scan(
			&i.UserID,
			&i.LessonSlug,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.SolutionRevealedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSolutionRevealed = `-- name: MarkSolutionRevealed :exec
INSERT INTO user_lesson (user_id, lesson_slug, status, solution_revealed_at)
VALUES ($1, $2, 'in_progress', now())
ON CONFLICT (user_id, lesson_slug) DO UPDATE
SET solution_revealed_at = COALESCE(user_lesson.solution_revealed_at, now())
`

type MarkSolutionRevealedParams struct {
	UserID     uuid.UUID
	LessonSlug string
}

// An upsert rather than an update: a learner reaches this having submitted, and
// a submission does not require ever having opened the lesson page that creates
// the row. COALESCE keeps the first reveal, because "when did they give up on
// this" is asked of the first time, not the most recent.
func (q *Queries) MarkSolutionRevealed(ctx context.Context, arg MarkSolutionRevealedParams) error {
	_, err := q.db.Exec(ctx, markSolutionRevealed, arg.UserID, arg.LessonSlug)
	return err
}

const recordAttempt = `-- name: RecordAttempt :one
INSERT INTO exercise_attempt (user_id, lesson_slug, code, passed)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, lesson_slug, code, passed, created_at
`

type RecordAttemptParams struct {
	UserID     uuid.UUID
	LessonSlug string
	Code       string
	Passed     bool
}

func (q *Queries) RecordAttempt(ctx context.Context, arg RecordAttemptParams) (ExerciseAttempt, error) {
	row := q.db.QueryRow(ctx, recordAttempt,
		arg.UserID,
		arg.LessonSlug,
		arg.Code,
		arg.Passed,
	)
	var i ExerciseAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LessonSlug,
		&i.Code,
		&i.Passed,
		&i.CreatedAt,
	)
	return i, err
}

const upsertLessonProgress = `-- name: UpsertLessonProgress :one

INSERT INTO user_lesson (user_id, lesson_slug, status, completed_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, lesson_slug) DO UPDATE
SET status       = CASE
                       WHEN user_lesson.status = 'completed' THEN 'completed'
                       ELSE EXCLUDED.status
                   END,
    -- COALESCE so re-completing keeps the original timestamp: the interesting
    -- fact is when it was first finished, not most recently.
    completed_at = COALESCE(user_lesson.completed_at, EXCLUDED.completed_at)
RETURNING user_id, lesson_slug, status, started_at, completed_at, solution_revealed_at
`

type UpsertLessonProgressParams struct {
	UserID      uuid.UUID
	LessonSlug  string
	Status      string
	CompletedAt pgtype.Timestamptz
}

// Every query here is scoped by user_id. That scoping is the access control:
// there is no second check elsewhere that a row belongs to the caller, so a
// query that omits it is a data leak rather than a bug in a filter.
// Completion is sticky. Re-opening a finished lesson is an ordinary thing to
// do, and writing EXCLUDED.status unconditionally would demote it to
// in_progress while COALESCE below still kept its completed_at — a pair the
// table's CHECK constraint rejects outright, so this was a runtime error and
// not merely wrong data.
func (q *Queries) UpsertLessonProgress(ctx context.Context, arg UpsertLessonProgressParams) (UserLesson, error) {
	row := q.db.QueryRow(ctx, upsertLessonProgress,
		arg.UserID,
		arg.LessonSlug,
		arg.Status,
		arg.CompletedAt,
	)
	var i UserLesson
	err := row.Scan(
		&i.UserID,
		&i.LessonSlug,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.SolutionRevealedAt,
	)
	return i, err
}
