// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package authdb

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at, user_agent, ip)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, created_at, last_used_at, expires_at, user_agent, ip
`

type CreateSessionParams struct {
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	UserAgent *string
	Ip        *netip.Addr
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, password_hash, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE FROM sessions
WHERE user_id = $1
`

func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsForUser, userID)
	return err
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT
    sessions.id, sessions.user_id, sessions.token_hash, sessions.created_at, sessions.last_used_at, sessions.expires_at, sessions.user_agent, sessions.ip,
    users.id, users.email, users.password_hash, users.created_at, users.updated_at
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1
  AND sessions.expires_at > now()
`

type GetSessionWithUserRow struct {
	Session Session
	User    User
}

// Returns the session and its user together: every authenticated request needs
// both, and two round trips per request to assemble them is one too many.
// Expired rows are excluded here rather than deleted on read, so the lookup
// stays a pure read and cleanup can happen on its own schedule.
func (q *Queries) GetSessionWithUser(ctx context.Context, tokenHash []byte) (GetSessionWithUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithUser, tokenHash)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.UserID,
		&i.Session.TokenHash,
		&i.Session.CreatedAt,
		&i.Session.LastUsedAt,
		&i.Session.ExpiresAt,
		&i.Session.UserAgent,
		&i.Session.Ip,
		&i.User.ID,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at, updated_at FROM users
WHERE lower(email) = lower($1::text)
`

// Addresses are compared case-insensitively; the unique index is on
// lower(email), so this predicate is what makes the lookup use it.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_used_at = now(),
    expires_at   = $2
WHERE id = $1
`

type TouchSessionParams struct {
	ID        uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.ExpiresAt)
	return err
}
